// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC0_PEk9TsQqvkHJUmBaDh_mA6Z26hf8iA',
    appId: '1:96692674550:web:6bde69521247610edf31d7',
    messagingSenderId: '96692674550',
    projectId: 'trainable-problem-solver',
    authDomain: 'trainable-problem-solver.firebaseapp.com',
    storageBucket: 'trainable-problem-solver.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA7IS9yvbahMdhwdDhEdSTsfhZrWvc6aEA',
    appId: '1:96692674550:android:0709c51bb8b4318adf31d7',
    messagingSenderId: '96692674550',
    projectId: 'trainable-problem-solver',
    storageBucket: 'trainable-problem-solver.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC3S9WoyiTrve8HjqVAMJtL4heeZzdbKGY',
    appId: '1:96692674550:ios:4a07c354ea5ca1c3df31d7',
    messagingSenderId: '96692674550',
    projectId: 'trainable-problem-solver',
    storageBucket: 'trainable-problem-solver.firebasestorage.app',
    iosBundleId: 'com.vprihogenko.trainableProblemSolver',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC3S9WoyiTrve8HjqVAMJtL4heeZzdbKGY',
    appId: '1:96692674550:ios:4a07c354ea5ca1c3df31d7',
    messagingSenderId: '96692674550',
    projectId: 'trainable-problem-solver',
    storageBucket: 'trainable-problem-solver.firebasestorage.app',
    iosBundleId: 'com.vprihogenko.trainableProblemSolver',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCt8qRgwFhjAOMt708RlhyrW1DRrUkyzeU',
    appId: '1:96692674550:web:666cb17cece36d40df31d7',
    messagingSenderId: '96692674550',
    projectId: 'trainable-problem-solver',
    authDomain: 'trainable-problem-solver.firebaseapp.com',
    storageBucket: 'trainable-problem-solver.firebasestorage.app',
  );

}